### ISSUE TITLE
Plugin doesn't work with Gatsby ^2.24.33

### ISSUE THREAD

**Issue by kennedybg** [ehrencrona/gatsby-plugin-testing#1]
Hello! Thank you for this plugin, it helped me a lot!
I've started to use it a few months ago and yesterday I needed to update the project and... It crashed...
I searched for the reason and found that in the new versions of Gatsby, the StaticQueries directory has [changed](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#bug-fixes-34). So I tried to fix it and I've founded a solution that works for the old versions and the new ones. Would be great to have your opinion about this and, if you allow me, I would like to merge my PR (after code review).

Sorry if I wrote a wrong sentence, I'm still learning English. I'm from Brazil. ;)

Thanks in advance.

**Comment by ehrencrona** [comment]
Happy you like it! Nothing wrong with your English 👍 

I've released this as version 0.3.2. Thanks for the contribution!
