### ISSUE TITLE
Problem after updating Gatsby

### ISSUE THREAD

**Issue by mohsenkhanpour** [ehrencrona/gatsby-plugin-testing#3]
Hey thanks for the great plugin, it really saves us a lot of time configuring testing.
After updating Gatsby to latest version, when I start dev server and compilation finishes, gatsby-plugin-testing indefinitely shows a spinner as if it is doing something, although development bundle has finished being created.
```
success write out requires - 0.001s
success Re-building development bundle - 2.169s
⠄ [gatsby-plugin-testing] stored static queries
```

**Comment by ehrencrona** [comment]
Does this refer to the plugin version 0.3.2 and Gatsby 2.27.3?

**Comment by mohsenkhanpour** [comment]
Yes, it certainly wasn't like that before the update.
```
gatsby: 2.27.3 => 2.27.3 
gatsby-plugin-testing: ^0.3.2 => 0.3.2 
```

**Comment by ehrencrona** [comment]
I can't reproduce this. This happens as soon as you run `develop`? The storing queries terminates fine for me on 2.27.3.

Can you provide a repo with a reproduction?

**Comment by mohsenkhanpour** [comment]
Not as soon as I run `develop`, the initial development bundle finishes and storing queries terminates. 
However as soon as I edit & save a file, `Re-building development bundle` finishes however `⠄ [gatsby-plugin-testing] stored static queries` keeps spinning.

I will try to provide a repo reproduction soon.

**Comment by mohsenkhanpour** [comment]
@ehrencrona I tried with a new repo based on gatsby default starter and couldn't reproduce.
However on the same project I am working on, it happened once when I tried again, and didn't happen next time I tried. 
It might be related to another plugin, I will close this issue now.
Thanks for the great plugin.
